#include "Keystate.h"

namespace eng::input {

#define ENUM_NAME KeyPhase
ENUM_TOSTRING_START
ENUM_TOSTRING_CASE(Down)
ENUM_TOSTRING_CASE(Pressed)
ENUM_TOSTRING_CASE(Up)
ENUM_TOSTRING_END
#undef ENUM_NAME

#define ENUM_NAME KeyboardKeys
ENUM_TOSTRING_START
ENUM_TOSTRING_CASE(W)
ENUM_TOSTRING_CASE(A)
ENUM_TOSTRING_CASE(S)
ENUM_TOSTRING_CASE(D)
ENUM_TOSTRING_CASE(Space)
ENUM_TOSTRING_CASE(Q)
ENUM_TOSTRING_CASE(E)
ENUM_TOSTRING_END
#undef ENUM_NAME

#define ENUM_NAME GamepadKeys
ENUM_TOSTRING_START
ENUM_TOSTRING_CASE(Up)
ENUM_TOSTRING_CASE(Left)
ENUM_TOSTRING_CASE(Down)
ENUM_TOSTRING_CASE(Right)
ENUM_TOSTRING_CASE(Start)
ENUM_TOSTRING_CASE(Back)
ENUM_TOSTRING_CASE(Lthumb)
ENUM_TOSTRING_CASE(Rthumb)
ENUM_TOSTRING_CASE(Lshoulder)
ENUM_TOSTRING_CASE(Rshoulder)
ENUM_TOSTRING_CASE(A)
ENUM_TOSTRING_CASE(B)
ENUM_TOSTRING_CASE(X)
ENUM_TOSTRING_CASE(Y)
ENUM_TOSTRING_END
#undef ENUM_NAME

}